### ISSUE TITLE
"About" section is offset when resolution is higher than 1200px

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-lavogue#7]
![offset](https://cloud.githubusercontent.com/assets/539962/8625016/d4f36240-26f0-11e5-941f-1b1d145efcdf.jpg)

I know the exact code you'll need to fix it, but I want you to figure it out before 11p today. It's an easy fix and it's got to do with Bootstrap classes.

Due date: 
7-10-15 11p

**Comment by AaronAguilar** [comment]
Does it have to do with columns exactly? I've tried a lot of different things: https://github.com/EditLLC/client-lavogue/commits/gh-pages 
but none have really seem to be working.

**Comment by rodneystrong** [comment]
hahaha woow, sorry i forgot to get back to you on this. 

yea you definitely tried quite a bit of things. good effort ! seriously, i'm actually really happy you attempted all these options (and made separate commits for them!).  

take another stab at this. dont spend more than 1.5hrs though. after that comment here again with your commits.

hint: yes, it has to do with columns but also the .container class as well. in your first commit https://github.com/EditLLC/client-lavogue/commit/8cf2e35ff1a2b2bc35f7b58024fa78107f16f059 you attempted the .container-fluid class. why? 

keep at it, i got faith in you.

**Comment by rodneystrong** [comment]
@AaronAguilar given how you solved the issue for takobbq on the bg-color, i have a feeling you should be able to fix this one.. 

Let me know if you've spent more than 1.5hrs trying to solve this again. If so, I'll fix it and walk you through it.

**Comment by AaronAguilar** [comment]
It's fixed! I had to put the container inside my bg-gray class in order to have the black background across and have a container. I also removed the offset since it's in a container so it didn't look squished. 

<img width="1093" alt="screen shot 2015-07-23 at 8 44 32 pm" src="https://cloud.githubusercontent.com/assets/10875354/8867211/b52aa000-317b-11e5-87a5-b2aeac4ea689.png">

**Comment by rodneystrong** [comment]
@AaronAguilar very good job sir! 

Glad you found it and fixed it without using too much code.
